
export const products = [
    {
        id: crypto.randomUUID(),
        image:'relogio-1', 
        tags:['esportivo'],
        name:'Chronos' ,
        descriptions:'Design robusto com estilo esportivo e moderno.',
        price: 982.99, 
    },
    {
        id: crypto.randomUUID(),
        image:'relogio-2', 
        tags:['esportivo'],
        name:'Tempus Noir' ,
        descriptions:'Elegância discreta com acabamento sofisticado.',
        price: 982.99, 
    },
    {
        id: crypto.randomUUID(),
        image:'relogio-3', 
        tags:['esportivo'],
        name:'Atlas Timekeeper' ,
        descriptions:'Visual forte e funcional para o dia a dia.',
        price: 982.99, 
    },
    {
        id: crypto.randomUUID(),
        image:'relogio-4', 
        tags:['esportivo'],
        name:'Vértice Prime' ,
        descriptions:' Clássico refinado com presença marcante.',
        price: 982.99, 
    },
    {
        id: crypto.randomUUID(),
        image:'relogio-5', 
        tags:['esportivo'],
        name:'Nebula One' ,
        descriptions:'Estilo tradicional com toque contemporâneo.',
        price: 982.99, 
    },
    {
        id: crypto.randomUUID(),
        image:'relogio-6', 
        tags:['esportivo'],
        name:'Eon Steel' ,
        descriptions:'Elegância metálica com visual atemporal.',
        price: 982.99, 
    },
    {
        id: crypto.randomUUID(),
        image:'relogio-7', 
        tags:['esportivo'],
        name:'Chronix Pulse' ,
        descriptions:'Design moderno com detalhes precisos.',
        price: 982.99, 
    },
    {
        id: crypto.randomUUID(),
        image:'relogio-8', 
        tags:['esportivo'],
        name:'Lumen Watch' ,
        descriptions:'Simples, elegante e fácil de combinar.',
        price: 982.99, 
    },
    {
        id: crypto.randomUUID(),
        image:'relogio-9', 
        tags:['esportivo'],
        name:'Orion Mark I' ,
        descriptions:' Estilo casual com personalidade marcante.',
        price: 982.99, 
    },
    {
        id: crypto.randomUUID(),
        image:'relogio-10', 
        tags:['esportivo'],
        name:'Irlandês' ,
        descriptions:'Casual e autêntico, com charme diferenciado.',
        price: 982.99, 
    },
    {
        id: crypto.randomUUID(),
        image:'relogio-11', 
        tags:['esportivo'],
        name:'Zenith Core' ,
        descriptions:'Clássico sofisticado para todas as ocasiões.',
        price: 982.99, 
    },
    {
        id: crypto.randomUUID(),
        image:'relogio-12', 
        tags:['esportivo'],
        name:'Cubano' ,
        descriptions:'Visual imponente com acabamento premium.',
        price: 982.99, 
    },
    {
        id: crypto.randomUUID(),
        image:'relogio-13', 
        tags:['esportivo'],
        name:'Astra Vault' ,
        descriptions:'Design moderno com toque urbano.',
        price: 982.99, 
    },
    {
        id: crypto.randomUUID(),
        image:'relogio-14', 
        tags:['esportivo'],
        name:'IronTick Classic' ,
        descriptions:'Estilo esportivo com visual resistente.',
        price: 982.99, 
    },

]