
export const products = [
    {
        id: '001',
        image:'relogio-1', 
        tags:['esportivo'],
        name:'Chronos' ,
        descriptions:'Design robusto com estilo esportivo e moderno.',
        price: 982.99, 
    },
    {
        id: '002',
        image:'relogio-2', 
        tags:['casual'],
        name:'Tempus Noir' ,
        descriptions:'Elegância discreta com acabamento sofisticado.',
        price: 982.99, 
    },
    {
        id: '003',
        image:'relogio-3', 
        tags:['casual'],
        name:'Atlas Timekeeper' ,
        descriptions:'Visual forte e funcional para o dia a dia.',
        price: 982.99, 
    },
    {
        id: '004',
        image:'relogio-4', 
        tags:['classico', 'luxo'],
        name:'Vértice Prime' ,
        descriptions:' Clássico refinado com presença marcante.',
        price: 982.99, 
    },
    {
        id: '005',
        image:'relogio-5', 
        tags:['classico', 'luxo'],
        name:'Nebula One' ,
        descriptions:'Estilo tradicional com toque contemporâneo.',
        price: 982.99, 
    },
    {
        id: 'classico01',
        image:'relogio-6', 
        tags:['classico', 'luxo'],
        name:'Eon Steel' ,
        descriptions:'Elegância metálica com visual atemporal.',
        price: 982.99, 
    },
    {
        id: '006',
        image:'relogio-7', 
        tags:['classico', 'importado'],
        name:'Chronix Pulse' ,
        descriptions:'Design moderno com detalhes precisos.',
        price: 982.99, 
    },
    {
        id: '007',
        image:'relogio-8', 
        tags:['classico', 'luxo'],
        name:'Lumen Watch' ,
        descriptions:'Simples, elegante e fácil de combinar.',
        price: 982.99, 
    },
    {
        id: '009',
        image:'relogio-9', 
        tags:['classico', 'luxo'],
        name:'Orion Mark I' ,
        descriptions:' Estilo casual com personalidade marcante.',
        price: 982.99, 
    },
    {
        id: '010',
        image:'relogio-10', 
        tags:['esportivo', 'casual'],
        name:'Irlandês' ,
        descriptions:'Casual e autêntico, com charme diferenciado.',
        price: 982.99, 
    },
    {
        id: '011',
        image:'relogio-11', 
        tags:['classico', 'luxo'],
        name:'Zenith Core' ,
        descriptions:'Clássico sofisticado para todas as ocasiões.',
        price: 982.99, 
    },
    {
        id: '012',
        image:'relogio-12', 
        tags:['automático', 'importado'],
        name:'Cubano' ,
        descriptions:'Visual imponente com acabamento premium.',
        price: 982.99, 
    },
    {
        id: '013',
        image:'relogio-13', 
        tags:['casual'],
        name:'Astra Vault' ,
        descriptions:'Design moderno com toque urbano.',
        price: 982.99, 
    },
    {
        id: '014',
        image:'relogio-14', 
        tags:['esportivo'],
        name:'IronTick Classic' ,
        descriptions:'Estilo esportivo com visual resistente.',
        price: 982.99, 
    }

]